//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Женская_сборная_по_баскетболу.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BasketballClubEntities : DbContext
    {
        private static Model.BasketballClubEntities _context = new Model.BasketballClubEntities();
        public BasketballClubEntities()
            : base("name=BasketballClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static Model.BasketballClubEntities GetContext()
        {
            if (_context == null)
                _context = new Model.BasketballClubEntities();
            return _context;
        }


        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Club> Club { get; set; }
        public virtual DbSet<Coach> Coach { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<PlayerHistory> PlayerHistory { get; set; }
        public virtual DbSet<Sponsor> Sponsor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TrainingHall> TrainingHall { get; set; }
        public virtual DbSet<Transport> Transport { get; set; }
    }
}
