//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Женская_сборная_по_баскетболу.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerHistory
    {
        public int Id { get; set; }
        public string ClubName { get; set; }
        public string Post { get; set; }
        public int GameNumber { get; set; }
        public string Role { get; set; }
        public double Height { get; set; }
        public double Weight { get; set; }
        public System.DateTime Date { get; set; }
        public int PlayerId { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
